/**
 * Supabase Database Types
 * 
 * This file mirrors the structure generated by `supabase gen types typescript`.
 * It provides full type safety for all database operations.
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type MealType = 'breakfast' | 'lunch' | 'dinner' | 'snack';

export interface Database {
  public: {
    Tables: {
      recipes: {
        Row: {
          id: string;
          user_id: string;
          name: string;
          description: string | null;
          image_url: string | null;
          category: string | null;
          tags: string[];
          prep_time_minutes: number | null;
          base_servings: number; // How many people the recipe serves
          source_url: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          name: string;
          description?: string | null;
          image_url?: string | null;
          category?: string | null;
          tags?: string[];
          prep_time_minutes?: number | null;
          base_servings?: number; // Default: 4
          source_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          name?: string;
          description?: string | null;
          image_url?: string | null;
          category?: string | null;
          tags?: string[];
          prep_time_minutes?: number | null;
          base_servings?: number;
          source_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'recipes_user_id_fkey';
            columns: ['user_id'];
            referencedRelation: 'users';
            referencedColumns: ['id'];
          }
        ];
      };
      ingredients: {
        Row: {
          id: string;
          recipe_id: string;
          name: string;
          quantity: number | null;
          unit: string | null;
          aisle: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          recipe_id: string;
          name: string;
          quantity?: number | null;
          unit?: string | null;
          aisle?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          recipe_id?: string;
          name?: string;
          quantity?: number | null;
          unit?: string | null;
          aisle?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'ingredients_recipe_id_fkey';
            columns: ['recipe_id'];
            referencedRelation: 'recipes';
            referencedColumns: ['id'];
          }
        ];
      };
      planned_meals: {
        Row: {
          id: string;
          user_id: string;
          recipe_id: string;
          date: string;
          meal_type: MealType;
          servings: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          recipe_id: string;
          date: string;
          meal_type: MealType;
          servings?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          recipe_id?: string;
          date?: string;
          meal_type?: MealType;
          servings?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'planned_meals_user_id_fkey';
            columns: ['user_id'];
            referencedRelation: 'users';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'planned_meals_recipe_id_fkey';
            columns: ['recipe_id'];
            referencedRelation: 'recipes';
            referencedColumns: ['id'];
          }
        ];
      };
      shopping_lists: {
        Row: {
          id: string;
          user_id: string;
          start_date: string;
          end_date: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          start_date: string;
          end_date: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          start_date?: string;
          end_date?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'shopping_lists_user_id_fkey';
            columns: ['user_id'];
            referencedRelation: 'users';
            referencedColumns: ['id'];
          }
        ];
      };
      shopping_list_items: {
        Row: {
          id: string;
          shopping_list_id: string;
          name: string;
          quantity: number | null;
          unit: string | null;
          aisle: string | null;
          checked: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          shopping_list_id: string;
          name: string;
          quantity?: number | null;
          unit?: string | null;
          aisle?: string | null;
          checked?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          shopping_list_id?: string;
          name?: string;
          quantity?: number | null;
          unit?: string | null;
          aisle?: string | null;
          checked?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'shopping_list_items_shopping_list_id_fkey';
            columns: ['shopping_list_id'];
            referencedRelation: 'shopping_lists';
            referencedColumns: ['id'];
          }
        ];
      };
    };
    Views: Record<string, never>;
    Functions: {
      generate_shopping_list: {
        Args: {
          p_start_date: string;
          p_end_date: string;
        };
        Returns: string;
      };
    };
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
}

// ============================================================================
// TYPE ALIASES
// ============================================================================
// Convenient aliases for common operations

/** Full recipe row from database */
export type Recipe = Database['public']['Tables']['recipes']['Row'];

/** Recipe data for insert operations */
export type RecipeInsert = Database['public']['Tables']['recipes']['Insert'];

/** Recipe data for update operations */
export type RecipeUpdate = Database['public']['Tables']['recipes']['Update'];

/** Full ingredient row from database */
export type Ingredient = Database['public']['Tables']['ingredients']['Row'];

/** Ingredient data for insert operations */
export type IngredientInsert = Database['public']['Tables']['ingredients']['Insert'];

/** Full planned meal row from database */
export type PlannedMeal = Database['public']['Tables']['planned_meals']['Row'];

/** Planned meal data for insert operations */
export type PlannedMealInsert = Database['public']['Tables']['planned_meals']['Insert'];

/** Planned meal data for update operations */
export type PlannedMealUpdate = Database['public']['Tables']['planned_meals']['Update'];

/** Full shopping list row from database */
export type ShoppingList = Database['public']['Tables']['shopping_lists']['Row'];

/** Full shopping list item row from database */
export type ShoppingListItem = Database['public']['Tables']['shopping_list_items']['Row'];

// ============================================================================
// FORM INPUT TYPES
// ============================================================================
// Types for form handling (without database-generated fields)

/** Form input for creating/editing ingredients */
export interface IngredientInput {
  name: string;
  quantity: number | null;
  unit: string | null;
  aisle: string | null;
}

/** Form input for creating/editing recipes */
export interface RecipeInput {
  name: string;
  description?: string | null;
  image_url?: string | null;
  category?: string | null;
  tags?: string[];
  prep_time_minutes?: number | null;
  base_servings?: number; // How many people the recipe serves (default 4)
  source_url?: string | null;
  ingredients: IngredientInput[];
}

/** Recipe with its ingredients loaded */
export interface RecipeWithIngredients extends Recipe {
  ingredients: Ingredient[];
}

/** Planned meal with recipe data loaded */
export interface PlannedMealWithRecipe extends PlannedMeal {
  recipe: Recipe;
}

/** Shopping list with items loaded */
export interface ShoppingListWithItems extends ShoppingList {
  items: ShoppingListItem[];
}
