/**
 * Supabase Database Types
 * 
 * This file mirrors the structure generated by `supabase gen types typescript`.
 * It provides full type safety for all database operations.
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type MealType = 'breakfast' | 'lunch' | 'dinner' | 'snack';

export interface Database {
  public: {
    Tables: {
      recipes: {
        Row: {
          id: string;
          user_id: string;
          name: string;
          description: string | null;
          image_url: string | null;
          category: string | null;
          tags: string[];
          prep_time_minutes: number | null;
          base_servings: number; // How many people the recipe serves
          source_url: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          name: string;
          description?: string | null;
          image_url?: string | null;
          category?: string | null;
          tags?: string[];
          prep_time_minutes?: number | null;
          base_servings?: number; // Default: 4
          source_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          name?: string;
          description?: string | null;
          image_url?: string | null;
          category?: string | null;
          tags?: string[];
          prep_time_minutes?: number | null;
          base_servings?: number;
          source_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'recipes_user_id_fkey';
            columns: ['user_id'];
            referencedRelation: 'users';
            referencedColumns: ['id'];
          }
        ];
      };
      ingredients: {
        Row: {
          id: string;
          recipe_id: string;
          name: string;
          quantity: number | null;
          unit: string | null;
          aisle: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          recipe_id: string;
          name: string;
          quantity?: number | null;
          unit?: string | null;
          aisle?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          recipe_id?: string;
          name?: string;
          quantity?: number | null;
          unit?: string | null;
          aisle?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'ingredients_recipe_id_fkey';
            columns: ['recipe_id'];
            referencedRelation: 'recipes';
            referencedColumns: ['id'];
          }
        ];
      };
      planned_meals: {
        Row: {
          id: string;
          user_id: string;
          recipe_id: string;
          date: string;
          meal_type: MealType;
          servings: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          recipe_id: string;
          date: string;
          meal_type: MealType;
          servings?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          recipe_id?: string;
          date?: string;
          meal_type?: MealType;
          servings?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'planned_meals_user_id_fkey';
            columns: ['user_id'];
            referencedRelation: 'users';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'planned_meals_recipe_id_fkey';
            columns: ['recipe_id'];
            referencedRelation: 'recipes';
            referencedColumns: ['id'];
          }
        ];
      };
      shopping_lists: {
        Row: {
          id: string;
          user_id: string;
          start_date: string;
          end_date: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          start_date: string;
          end_date: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          start_date?: string;
          end_date?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'shopping_lists_user_id_fkey';
            columns: ['user_id'];
            referencedRelation: 'users';
            referencedColumns: ['id'];
          }
        ];
      };
      shopping_list_items: {
        Row: {
          id: string;
          shopping_list_id: string;
          name: string;
          quantity: number | null;
          unit: string | null;
          aisle: string | null;
          checked: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          shopping_list_id: string;
          name: string;
          quantity?: number | null;
          unit?: string | null;
          aisle?: string | null;
          checked?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          shopping_list_id?: string;
          name?: string;
          quantity?: number | null;
          unit?: string | null;
          aisle?: string | null;
          checked?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'shopping_list_items_shopping_list_id_fkey';
            columns: ['shopping_list_id'];
            referencedRelation: 'shopping_lists';
            referencedColumns: ['id'];
          }
        ];
      };
      inventory: {
        Row: {
          id: string;
          user_id: string;
          name: string;
          quantity: number;
          unit: string | null;
          category: InventoryCategory;
          aisle: string | null;
          min_quantity: number;
          expiry_date: string | null;
          location: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          name: string;
          quantity?: number;
          unit?: string | null;
          category?: InventoryCategory;
          aisle?: string | null;
          min_quantity?: number;
          expiry_date?: string | null;
          location?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          name?: string;
          quantity?: number;
          unit?: string | null;
          category?: InventoryCategory;
          aisle?: string | null;
          min_quantity?: number;
          expiry_date?: string | null;
          location?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'inventory_user_id_fkey';
            columns: ['user_id'];
            referencedRelation: 'users';
            referencedColumns: ['id'];
          }
        ];
      };
      inventory_transactions: {
        Row: {
          id: string;
          inventory_id: string;
          type: InventoryTransactionType;
          quantity: number;
          quantity_before: number;
          quantity_after: number;
          planned_meal_id: string | null;
          note: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          inventory_id: string;
          type: InventoryTransactionType;
          quantity: number;
          quantity_before: number;
          quantity_after: number;
          planned_meal_id?: string | null;
          note?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          inventory_id?: string;
          type?: InventoryTransactionType;
          quantity?: number;
          quantity_before?: number;
          quantity_after?: number;
          planned_meal_id?: string | null;
          note?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'inventory_transactions_inventory_id_fkey';
            columns: ['inventory_id'];
            referencedRelation: 'inventory';
            referencedColumns: ['id'];
          }
        ];
      };
    };
    Views: Record<string, never>;
    Functions: {
      generate_shopping_list: {
        Args: {
          p_start_date: string;
          p_end_date: string;
        };
        Returns: string;
      };
      deduct_meal_ingredients: {
        Args: {
          p_planned_meal_id: string;
        };
        Returns: unknown;
      };
      generate_smart_shopping_list: {
        Args: {
          p_start_date: string;
          p_end_date: string;
        };
        Returns: Array<{
          name: string;
          needed_quantity: number;
          in_stock: number;
          to_buy: number;
          unit: string | null;
          aisle: string | null;
        }>;
      };
    };
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
}

// Inventory category type
export type InventoryCategory = 'food' | 'cleaning' | 'hygiene' | 'pet' | 'other';

// Inventory transaction type
export type InventoryTransactionType = 'add' | 'remove' | 'adjust' | 'meal_used' | 'expired';

// ============================================================================
// TYPE ALIASES
// ============================================================================
// Convenient aliases for common operations

/** Full recipe row from database */
export type Recipe = Database['public']['Tables']['recipes']['Row'];

/** Recipe data for insert operations */
export type RecipeInsert = Database['public']['Tables']['recipes']['Insert'];

/** Recipe data for update operations */
export type RecipeUpdate = Database['public']['Tables']['recipes']['Update'];

/** Full ingredient row from database */
export type Ingredient = Database['public']['Tables']['ingredients']['Row'];

/** Ingredient data for insert operations */
export type IngredientInsert = Database['public']['Tables']['ingredients']['Insert'];

/** Full planned meal row from database */
export type PlannedMeal = Database['public']['Tables']['planned_meals']['Row'];

/** Planned meal data for insert operations */
export type PlannedMealInsert = Database['public']['Tables']['planned_meals']['Insert'];

/** Planned meal data for update operations */
export type PlannedMealUpdate = Database['public']['Tables']['planned_meals']['Update'];

/** Full shopping list row from database */
export type ShoppingList = Database['public']['Tables']['shopping_lists']['Row'];

/** Full shopping list item row from database */
export type ShoppingListItem = Database['public']['Tables']['shopping_list_items']['Row'];

// ============================================================================
// FORM INPUT TYPES
// ============================================================================
// Types for form handling (without database-generated fields)

/** Form input for creating/editing ingredients */
export interface IngredientInput {
  name: string;
  quantity: number | null;
  unit: string | null;
  aisle: string | null;
}

/** Form input for creating/editing recipes */
export interface RecipeInput {
  name: string;
  description?: string | null;
  image_url?: string | null;
  category?: string | null;
  tags?: string[];
  prep_time_minutes?: number | null;
  base_servings?: number; // How many people the recipe serves (default 4)
  source_url?: string | null;
  ingredients: IngredientInput[];
}

/** Recipe with its ingredients loaded */
export interface RecipeWithIngredients extends Recipe {
  ingredients: Ingredient[];
}

/** Planned meal with recipe data loaded */
export interface PlannedMealWithRecipe extends PlannedMeal {
  recipe: Recipe;
}

/** Shopping list with items loaded */
export interface ShoppingListWithItems extends ShoppingList {
  items: ShoppingListItem[];
}

// ============================================================================
// INVENTORY TYPES
// ============================================================================

/** Full inventory item row from database */
export type InventoryItem = Database['public']['Tables']['inventory']['Row'];

/** Inventory item data for insert operations */
export type InventoryItemInsert = Database['public']['Tables']['inventory']['Insert'];

/** Inventory item data for update operations */
export type InventoryItemUpdate = Database['public']['Tables']['inventory']['Update'];

/** Full inventory transaction row from database */
export type InventoryTransaction = Database['public']['Tables']['inventory_transactions']['Row'];

/** Form input for creating/editing inventory items */
export interface InventoryInput {
  name: string;
  quantity: number;
  unit?: string | null;
  category?: InventoryCategory;
  aisle?: string | null;
  min_quantity?: number;
  expiry_date?: string | null;
  location?: string | null;
}

/** Smart shopping list item from RPC function */
export interface SmartShoppingItem {
  name: string;
  needed_quantity: number;
  in_stock: number;
  to_buy: number;
  unit: string | null;
  aisle: string | null;
}

/** Category labels in French */
export const INVENTORY_CATEGORY_LABELS: Record<InventoryCategory, string> = {
  food: '🍎 Aliments',
  cleaning: '🧹 Ménager',
  hygiene: '🧴 Hygiène',
  pet: '🐕 Animaux',
  other: '📦 Autre',
};

/** Location labels in French */
export const INVENTORY_LOCATION_LABELS: Record<string, string> = {
  frigo: '❄️ Réfrigérateur',
  congelateur: '🧊 Congélateur',
  placard: '🚪 Placard',
  salle_de_bain: '🚿 Salle de bain',
  garage: '🏠 Garage',
  other: '📍 Autre',
};

